print("FFFFFFF EEEEEEE RRRRRR")
print("F       E       R      R")
print("F       E       R      R")
print("FFFFF   EEEEE   RRRRRR")
print("F       E       R   R")
print("F       E       R    R") 
print("F       EEEEEEE R     R")