print("+---------------------------------------------------------+")
print("| September 2024                                          |")
print("|  Dear Fernando,                                         |")
print("|                                                         |")
print("|      I'm feeling really good today                      |")
print("|      In the future, I plan to look at these codes and   |")
print("|      say \"I can\'t believe I did that\"                   |")
print("|                                                         |")
print("|                                          Fernando       |")
print("+---------------------------------------------------------+")